package agc.playground.core.domain.models

/**
 * Created by Amadou on 26/08/2025
 *
 */

enum class Tag(val label: String) {
    PIZZA("Pizza"),
    ITALIAN("Italian"),
    VEGETARIAN("Vegetarian"),
    STIR_FRY("Stir-fry"),
    ASIAN("Asian"),
    COOKIES("Cookies"),
    DESSERT("Dessert"),
    BAKING("Baking"),
    PASTA("Pasta"),
    CHICKEN("Chicken"),
    SALSA("Salsa"),
    SALAD("Salad"),
    QUINOA("Quinoa"),
    BRUSCHETTA("Bruschetta"),
    BEEF("Beef"),
    CAPRESE("Caprese"),
    SHRIMP("Shrimp"),
    BIRYANI("Biryani"),
    MAIN_COURSE("Main course"),
    INDIAN("Indian"),
    PAKISTANI("Pakistani"),
    KARAHI("Karahi"),
    KEEMA("Keema"),
    POTATOES("Potatoes"),
    KEBABS("Kebabs"),
    SAAG("Saag"),
    ROTI("Roti"),
    RAMEN("Ramen"),
    JAPANESE("Japanese"),
    SOUP("Soup"),
    TAGINE("Tagine"),
    CHICKPEA("Chickpea"),
    MOROCCAN("Moroccan"),
    BIBIMBAP("Bibimbap"),
    KOREAN("Korean"),
    RICE("Rice"),
    MOUSSAKA("Moussaka"),
    GREEK("Greek"),
    BUTTER_CHICKEN("Butter chicken"),
    CURRY("Curry"),
    THAI("Thai"),
    LASSI("Lassi"),
    MANGO("Mango"),
    TIRAMISU("Tiramisu"),
    TURKISH("Turkish"),
    GRILLING("Grilling"),
    SMOOTHIE("Smoothie"),
    BLUEBERRY("Blueberry"),
    BANANA("Banana"),
    ELOTE("Elote"),
    MEXICAN("Mexican"),
    STREET_FOOD("Street food"),
    BORSCHT("Borscht"),
    RUSSIAN("Russian"),
    DOSA("Dosa"),
    FALAFEL("Falafel"),
    LEBANESE("Lebanese"),
    WRAP("Wrap"),
    CAIPIRINHA("Caipirinha"),
    BRAZILIAN("Brazilian"),
    COCKTAIL("Cocktail"),
    PATATAS_BRAVAS("Patatas bravas"),
    SPANISH("Spanish"),
    SPRING_ROLLS("Spring rolls"),
    VIETNAMESE("Vietnamese"),
    QUINOA_SALAD("Quinoa salad"),
    MEDITERRANEAN("Mediterranean"),
    MATCHA_ICE_CREAM("Matcha ice cream"),
    BRIGADEIROS("Brigadeiros"),
    ENCHILADAS("Enchiladas"),
    SHRIMP_CURRY("Shrimp curry"),
    SPANAKOPITA("Spanakopita"),
    COUSCOUS_SALAD("Couscous salad"),
    MOJITO("Mojito"),
    CUBAN("Cuban"),
    TERIYAKI_CHICKEN("Teriyaki chicken"),
    MANGO_SALSA("Mango salsa"),
    SHRIMP_STIR_FRY("Shrimp stir-fry"),
    QUICK("Quick"),
    MARGHERITA_PIZZA("Margherita pizza"),
    PESTO_PASTA("Pesto pasta"),
    CHICKEN_SKEWERS("Chicken skewers"),
    HAWAIIAN("Hawaiian"),
    SUSHI_ROLLS("Sushi rolls"),
    CHICKPEA_SALAD("Chickpea salad"),
    PINEAPPLE("Pineapple"),
    COCONUT("Coconut");

    companion object {
        fun fromLabel(label: String): Tag? =
            entries.firstOrNull { it.label.equals(label, ignoreCase = true) }
    }
}
