name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean + Lint
        run: ./gradlew clean :app:lintDebug --stacktrace

      - name: Run unit tests
        run: ./gradlew :core:test :app:testDebugUnitTest --stacktrace

      - name: Assemble debug APK
        run: ./gradlew :app:assembleDebug --stacktrace
